### PR TITLE
record class and Record list

### PR DESCRIPTION
**Pull request by eeelizzabeth**
I messed around with the content view, so just a heads up, if you changed it too.

### CODE REVIEW

**Comment by irismanriquezc** [comment]
I think this should be fine!

**Review by irismanriquezc — COMMENTED** [review]
I do not think that this will cause any issues.

**Review by irismanriquezc — APPROVED** [review]
Merging this onto the master should be done before I start to mess with the database incorportation.

**Review by mayca1998 — COMMENTED** [review]
Should be fine

**Review by juhipark — APPROVED** [review]
looks good

**Review by mayca1998 — APPROVED** [review]
should be fine

**Pull request closed without merging**
